import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { PlayCircle, RotateCcw, Route as RouteIcon, ShieldAlert } from "lucide-react";
import { toast } from "sonner";

import { AppShell } from "@/components/nari/app-shell";
import { Gate } from "@/components/nari/gate";
import { SimControls } from "@/components/nari/sim-controls";
import { DemoBadge, GlassCard, SectionTitle } from "@/components/nari/ui-kit";
import { useNari } from "@/lib/nari/store";

export const Route = createFileRoute("/demo")({
  head: () => ({
    meta: [
      { title: "Demo Mode — NariRide hackathon walkthrough" },
      {
        name: "description",
        content: "Run the scripted NariRide demo: normal ride, route deviation, risk escalation and SOS response.",
      },
      { property: "og:title", content: "Demo Mode — NariRide" },
      { property: "og:description", content: "A deterministic walkthrough of deviation detection and SOS." },
    ],
  }),
  component: () => (
    <Gate>
      <Demo />
    </Gate>
  ),
});

const SCRIPT = [
  { step: "1", title: "Start demo ride", body: "Loads a deterministic ride from the first two saved demo places." },
  { step: "2", title: "Normal route", body: "Risk stays SAFE while the vehicle tracks the expected polyline." },
  { step: "3", title: "Trigger deviation", body: "Pick Suspicious or Severe deviation to watch the score escalate." },
  { step: "4", title: "Safety check", body: "NariRide asks if you're safe and explains why risk rose." },
  { step: "5", title: "Activate SOS", body: "Contacts are alerted (simulated) and police stations are surfaced." },
  { step: "6", title: "Dispatch view", body: "Open the response dashboard to resolve the incident." },
];

function Demo() {
  const { state, activeRide, startDemo, resetDemo, triggerSos } = useNari();
  const navigate = useNavigate();

  return (
    <AppShell title="Demo Mode" subtitle="Deterministic, offline, judge-ready walkthrough">
      <div className="space-y-4">
        <GlassCard strong className="space-y-3 border-accent/40">
          <div className="flex items-center justify-between">
            <p className="text-sm font-semibold">Guided demo</p>
            <DemoBadge />
          </div>
          <p className="text-[11px] leading-snug text-muted-foreground">
            Everything runs locally: no paid APIs, no backend, no live SMS. The GPS stream is generated by a
            deterministic simulator so each run behaves identically.
          </p>
          <div className="grid gap-2">
            <button
              type="button"
              onClick={() => {
                startDemo();
                toast.success("Demo ride started");
                void navigate({ to: "/ride" });
              }}
              className="flex w-full items-center justify-center gap-2 rounded-2xl bg-brand-gradient px-4 py-3.5 text-sm font-bold text-primary-foreground"
            >
              <PlayCircle className="size-4" aria-hidden="true" /> Start demo ride
            </button>
            <button
              type="button"
              onClick={() => {
                if (!activeRide) {
                  toast.error("Start the demo ride first");
                  return;
                }
                const incident = triggerSos();
                if (incident) {
                  toast.error("SOS activated (simulated)");
                  void navigate({ to: "/sos" });
                }
              }}
              className="flex w-full items-center justify-center gap-2 rounded-2xl border border-critical/50 bg-critical/15 px-4 py-3.5 text-sm font-bold text-critical"
            >
              <ShieldAlert className="size-4" aria-hidden="true" /> Force SOS scenario
            </button>
            <button
              type="button"
              onClick={() => {
                resetDemo();
                toast.info("Demo data reset");
              }}
              className="flex w-full items-center justify-center gap-2 rounded-2xl border border-border px-4 py-3 text-sm font-semibold text-muted-foreground"
            >
              <RotateCcw className="size-4" aria-hidden="true" /> Reset demo data
            </button>
          </div>
        </GlassCard>

        {activeRide ? <SimControls /> : null}

        <div>
          <SectionTitle title="Demo script" />
          <GlassCard className="space-y-3">
            {SCRIPT.map((s) => (
              <div key={s.step} className="flex gap-3">
                <span className="grid size-7 shrink-0 place-items-center rounded-full bg-accent/15 text-xs font-bold text-accent">
                  {s.step}
                </span>
                <div>
                  <p className="text-sm font-semibold">{s.title}</p>
                  <p className="text-[11px] leading-snug text-muted-foreground">{s.body}</p>
                </div>
              </div>
            ))}
          </GlassCard>
        </div>

        <div>
          <SectionTitle title="Current demo state" />
          <GlassCard className="space-y-1 text-[11px] text-muted-foreground">
            <p className="flex items-center gap-1.5 text-sm font-semibold text-foreground">
              <RouteIcon className="size-4 text-accent" aria-hidden="true" />
              {activeRide ? `Ride ${activeRide.id} · ${activeRide.status}` : "No active demo ride"}
            </p>
            <p>Simulator mode: {state.sim.mode}</p>
            <p>Rides recorded: {state.rides.length}</p>
            <p>Incidents: {state.incidents.length} · Alerts: {state.notifications.length}</p>
          </GlassCard>
        </div>
      </div>
    </AppShell>
  );
}
