/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArrivalRouteImport } from './routes/arrival'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookRouteImport } from './routes/book'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as NightRouteImport } from './routes/night'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RideRouteImport } from './routes/ride'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as SosRouteImport } from './routes/sos'
import { Route as TrustedRouteImport } from './routes/trusted'
import { Route as PartnerIndexRouteImport } from './routes/partner.index'
import { Route as PartnerDashboardRouteImport } from './routes/partner.dashboard'
import { Route as PartnerEarningsRouteImport } from './routes/partner.earnings'
import { Route as PartnerOnboardingRouteImport } from './routes/partner.onboarding'
import { Route as PartnerRideRouteImport } from './routes/partner.ride'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArrivalRoute = ArrivalRouteImport.update({
  id: '/arrival',
  path: '/arrival',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const NightRoute = NightRouteImport.update({
  id: '/night',
  path: '/night',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RideRoute = RideRouteImport.update({
  id: '/ride',
  path: '/ride',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustedRoute = TrustedRouteImport.update({
  id: '/trusted',
  path: '/trusted',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerIndexRoute = PartnerIndexRouteImport.update({
  id: '/partner/',
  path: '/partner/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerDashboardRoute = PartnerDashboardRouteImport.update({
  id: '/partner/dashboard',
  path: '/partner/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerEarningsRoute = PartnerEarningsRouteImport.update({
  id: '/partner/earnings',
  path: '/partner/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerOnboardingRoute = PartnerOnboardingRouteImport.update({
  id: '/partner/onboarding',
  path: '/partner/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRideRoute = PartnerRideRouteImport.update({
  id: '/partner/ride',
  path: '/partner/ride',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arrival': typeof ArrivalRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/contacts': typeof ContactsRoute
  '/demo': typeof DemoRoute
  '/dispatch': typeof DispatchRoute
  '/history': typeof HistoryRoute
  '/night': typeof NightRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/ride': typeof RideRoute
  '/safety': typeof SafetyRoute
  '/sos': typeof SosRoute
  '/trusted': typeof TrustedRoute
  '/partner/dashboard': typeof PartnerDashboardRoute
  '/partner/earnings': typeof PartnerEarningsRoute
  '/partner/onboarding': typeof PartnerOnboardingRoute
  '/partner/ride': typeof PartnerRideRoute
  '/partner/': typeof PartnerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arrival': typeof ArrivalRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/contacts': typeof ContactsRoute
  '/demo': typeof DemoRoute
  '/dispatch': typeof DispatchRoute
  '/history': typeof HistoryRoute
  '/night': typeof NightRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/ride': typeof RideRoute
  '/safety': typeof SafetyRoute
  '/sos': typeof SosRoute
  '/trusted': typeof TrustedRoute
  '/partner/dashboard': typeof PartnerDashboardRoute
  '/partner/earnings': typeof PartnerEarningsRoute
  '/partner/onboarding': typeof PartnerOnboardingRoute
  '/partner/ride': typeof PartnerRideRoute
  '/partner': typeof PartnerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arrival': typeof ArrivalRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/contacts': typeof ContactsRoute
  '/demo': typeof DemoRoute
  '/dispatch': typeof DispatchRoute
  '/history': typeof HistoryRoute
  '/night': typeof NightRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/ride': typeof RideRoute
  '/safety': typeof SafetyRoute
  '/sos': typeof SosRoute
  '/trusted': typeof TrustedRoute
  '/partner/dashboard': typeof PartnerDashboardRoute
  '/partner/earnings': typeof PartnerEarningsRoute
  '/partner/onboarding': typeof PartnerOnboardingRoute
  '/partner/ride': typeof PartnerRideRoute
  '/partner/': typeof PartnerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arrival'
    | '/auth'
    | '/book'
    | '/contacts'
    | '/demo'
    | '/dispatch'
    | '/history'
    | '/night'
    | '/onboarding'
    | '/profile'
    | '/ride'
    | '/safety'
    | '/sos'
    | '/trusted'
    | '/partner/dashboard'
    | '/partner/earnings'
    | '/partner/onboarding'
    | '/partner/ride'
    | '/partner/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arrival'
    | '/auth'
    | '/book'
    | '/contacts'
    | '/demo'
    | '/dispatch'
    | '/history'
    | '/night'
    | '/onboarding'
    | '/profile'
    | '/ride'
    | '/safety'
    | '/sos'
    | '/trusted'
    | '/partner/dashboard'
    | '/partner/earnings'
    | '/partner/onboarding'
    | '/partner/ride'
    | '/partner'
  id:
    | '__root__'
    | '/'
    | '/arrival'
    | '/auth'
    | '/book'
    | '/contacts'
    | '/demo'
    | '/dispatch'
    | '/history'
    | '/night'
    | '/onboarding'
    | '/profile'
    | '/ride'
    | '/safety'
    | '/sos'
    | '/trusted'
    | '/partner/dashboard'
    | '/partner/earnings'
    | '/partner/onboarding'
    | '/partner/ride'
    | '/partner/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArrivalRoute: typeof ArrivalRoute
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  ContactsRoute: typeof ContactsRoute
  DemoRoute: typeof DemoRoute
  DispatchRoute: typeof DispatchRoute
  HistoryRoute: typeof HistoryRoute
  NightRoute: typeof NightRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  RideRoute: typeof RideRoute
  SafetyRoute: typeof SafetyRoute
  SosRoute: typeof SosRoute
  TrustedRoute: typeof TrustedRoute
  PartnerDashboardRoute: typeof PartnerDashboardRoute
  PartnerEarningsRoute: typeof PartnerEarningsRoute
  PartnerOnboardingRoute: typeof PartnerOnboardingRoute
  PartnerRideRoute: typeof PartnerRideRoute
  PartnerIndexRoute: typeof PartnerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arrival': {
      id: '/arrival'
      path: '/arrival'
      fullPath: '/arrival'
      preLoaderRoute: typeof ArrivalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/night': {
      id: '/night'
      path: '/night'
      fullPath: '/night'
      preLoaderRoute: typeof NightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ride': {
      id: '/ride'
      path: '/ride'
      fullPath: '/ride'
      preLoaderRoute: typeof RideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trusted': {
      id: '/trusted'
      path: '/trusted'
      fullPath: '/trusted'
      preLoaderRoute: typeof TrustedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/': {
      id: '/partner/'
      path: '/partner'
      fullPath: '/partner/'
      preLoaderRoute: typeof PartnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/dashboard': {
      id: '/partner/dashboard'
      path: '/partner/dashboard'
      fullPath: '/partner/dashboard'
      preLoaderRoute: typeof PartnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/earnings': {
      id: '/partner/earnings'
      path: '/partner/earnings'
      fullPath: '/partner/earnings'
      preLoaderRoute: typeof PartnerEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/onboarding': {
      id: '/partner/onboarding'
      path: '/partner/onboarding'
      fullPath: '/partner/onboarding'
      preLoaderRoute: typeof PartnerOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/ride': {
      id: '/partner/ride'
      path: '/partner/ride'
      fullPath: '/partner/ride'
      preLoaderRoute: typeof PartnerRideRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArrivalRoute: ArrivalRoute,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  ContactsRoute: ContactsRoute,
  DemoRoute: DemoRoute,
  DispatchRoute: DispatchRoute,
  HistoryRoute: HistoryRoute,
  NightRoute: NightRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  RideRoute: RideRoute,
  SafetyRoute: SafetyRoute,
  SosRoute: SosRoute,
  TrustedRoute: TrustedRoute,
  PartnerDashboardRoute: PartnerDashboardRoute,
  PartnerEarningsRoute: PartnerEarningsRoute,
  PartnerOnboardingRoute: PartnerOnboardingRoute,
  PartnerRideRoute: PartnerRideRoute,
  PartnerIndexRoute: PartnerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
